<script type="text/javascript" src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/js/modules/zfgmodule.js"></script>
Groupmodule Management<hr>
<?php echo $this->message; ?>
<input type="button" value="Add Groupmodule" onclick="addgmodule();"/>
<table border=1>
    <tr>
        <td>Groupmodule Name</td>
        <td>Choices</td>
    </tr>
    
    <?php foreach($this->groupmodule as $key=>$row){ ?>
    
    <form class="frmup_<?=$key?>"  name="frmup_<?=$key?>" method="post" action="<?=$this->baseUrl()?>/zfgroupmodules/index/update">
        <input type="hidden" name="groupmodule_id" value="<?=$row->groupmodule_id?>"/>
    <tr class="gmodulehide_<?=$key?>" style="display:none;">
        <td>
            <input type="text" name="groupmodule_name" value="<?=$row->groupmodule_name?>"/>
        </td>
        <td><?php if ($row->is_locked==1) {     ?>
                <img src="<?=$this->baseUrl()."/themes/".Zend_Registry::get('theme')."/img/icons/core.gif"?>"
                            title="Core Group Module" onmouseover="this.style.cursor='pointer'"/><?php } else{  ?>
                <!-- update -->
                <a onclick="document.forms['frmup_<?=$key?>'].submit();" href="javascript:void(0);">
                    <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/save.gif" style="border:0px;"/>
                </a>    
                    |                    
                <!-- cancel -->
                <a onclick="cancel('<?=$key?>');" href="javascript:void(0);">
                    <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/cancel.png" style="border:0px;"/>
                </a>
            <?php } ?>
        </td>          
    </tr>
    </form>
    
     <tr class="gmodule_<?=$key?>">
        <td><?=$row->groupmodule_name?></td>
        <td><?php if ($row->is_locked==1) {     ?>
                <img src="<?=$this->baseUrl()."/themes/".Zend_Registry::get('theme')."/img/icons/core.gif"?>"
                            title="Core Group Module" onmouseover="this.style.cursor='pointer'"/><?php } else{  ?>
                <!-- Edit -->
                <a onclick="showedit('<?=$key?>');" href="javascript:void(0);">
                    <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/application_edit.png" style="border:0px;"/>
                </a>    
                    |                    
                <!-- Delete -->
                <a onclick="confirmdelete('<?=$row->groupmodule_id?>');" href="javascript:void(0);">
                    <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/Delete_24x24.png" style="border:0px;"/>
                </a>
            <?php } ?>
        </td>
     </tr>
    <?php } ?>
    
   <form class="frmadd"  name="frmadd" method="post" action="<?=$this->baseUrl()?>/zfgroupmodules/index/save">
    <tr class="gmoduleadd" style="display:none;">
        <td><input type="text" name="groupmodule_name"></td>
        <td>
            <a onclick="document.forms['frmadd'].submit();" href="javascript:void(0);">
                <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/save.gif" style="border:0px;"/>
            </a>
            |
            <a onclick="canceladd();" href="javascript:void(0);">
                <img src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/img/icons/cancel.png" style="border:0px;">
            </a>
        </td>
    </tr>
   </form>
   
</table>