<script type="text/javascript" src="<?=$this->baseUrl()?>/themes/<?=Zend_Registry::get('theme')?>/js/modules/zfpriv.js"></script>
zf_modules module
<hr>
<fieldset>
    Choose Group User :
    <select name="role_id" id="role_id">
        <?php foreach($this->guser as $key=>$row){ ?>
            <option value="<?=$row->role_id?>"><?=$row->role_name?></option>
        <?php } ?>
    </select> 
    <input type="button" onmouseover="this.style.cursor='pointer'" onclick="loaddata();" id="Load" name="Load" value="Load"/><span class="process"></span>
</fieldset>
<?=$this->message?>

<div id="loader" >
  
</div>

